# .github/workflows/app.yaml
name: PyTest
on: push

jobs:
  code_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.5"

      - name: Install dependancies
        run: |
          python3 -m pip install --upgrade pytest
          python3 -m pip install --upgrade pytest-cov
          python3 -m pip install --upgrade networkx

      - name: Install fgglib module
        run: |
          python3 -m pip install -e .

      - name: Run all tests
        run: |
          python3 -m pytest fgglib/autotesting/

      - name: Assert FG coverage
        run : |
          python3 -m pytest --cov fgglib/fg fgglib/autotesting/

      - name: Assert FGG coverage
        run : |
          python3 -m pytest --cov fgglib/fgg fgglib/autotesting/
